version: '3.8'

services:
  www:
    build: ./apache
    container_name: apache_webserver
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./public_html:/var/www/html:ro
      - ./logs/apache:/var/log/apache2
    depends_on:
      bbdd:
        condition: service_healthy
    environment:
      - APACHE_RUN_USER: "www-data"
      - APACHE_RUN_GROUP: "www-data"
    networks:
      - frontend

  bbdd:
    build: ./mysql
    container_naime: mysql_bbdd
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      - MYSQL_DATABASE: "${MYSQL_DATABASE}"
      - MYSQL_USER: "${MYSQL_USER}"
      - MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 3s
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_service
    restart: unless-stopped
    depends_on:
      bbdd:
        condition: service_healthy
      environment:
        PMA_HOST: "mysql"
        MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      ports:
        - "8081:80"
      networks:
        - frontend

  volumes:
    mysql_data:

  networks:
    frontend:
      driver: bridge
    backend:
      driver: bridge
