services:
  www:
    build: ./apache
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./public_html:/var/www/html:ro
      - ./logs/apache:/var/log/apache2
    depends_on:
      ddbb:
        condition: service_healthy
    environment:
      APACHE_RUN_USER: "www-data"
      APACHE_RUN_GROUP: "www-data"
    networks:
      - frontend
      - backend

  ddbb:
    image: mysql:9.2.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 3s
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      ddbb:
        condition: service_healthy
    environment:
      PMA_HOST: "ddbb"
      PMA_USER: "${PMA_USER}"
      PMA_PASSWORD: "${PMA_PASSWORD}"
    ports:
      - "8081:80"
    networks:
      - frontend
      - backend

volumes:
  mysql-data:
    driver: local

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true
